query getExamples {
    repository(owner: "Telebirr-telegram-bot", name: "Telebirr-telegram-bot") {
        object(expression: "master:examples") {
            ... on Tree {
                entries {
                    name
                }
            }
        }
    }
}
